Name:           ros-melodic-towr
Version:        1.4.0
Release:        0%{?dist}
Summary:        ROS towr package

Group:          Development/Libraries
License:        BSD
URL:            http://github.com/ethz-adrl/towr
Source0:        %{name}-%{version}.tar.gz

Requires:       eigen3-devel
Requires:       ros-melodic-catkin
Requires:       ros-melodic-ifopt
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  ros-melodic-ifopt

%description
A light-weight, Eigen-based C++ library for trajectory optimization for legged
robots. This library provides implementations for variables, costs and
constraints that can be used to represent a legged locomotion problem. The
resulting Nonlinear Programming Problem (NLP) can then be solved with off-the-
shelf solvers, e.g. Ipopt using the generic optimizer interface ifopt.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon Jul 30 2018 Alexander W. Winkler <alexander.w.winkler@gmail.com> - 1.4.0-0
- Autogenerated by Bloom

* Tue Jul 17 2018 Alexander W. Winkler <alexander.w.winkler@gmail.com> - 1.3.2-0
- Autogenerated by Bloom

* Thu Jul 12 2018 Alexander W. Winkler <winklera@ethz.ch> - 1.3.1-1
- Autogenerated by Bloom

